#language to use in travis containers
language: python
python:
    - "2.6"
install:
  - pip install -r Requirements.txt
  - pip install coveralls

script:
  - python -m pytest --cov
  
after_success: 
- coveralls
