#language to use in travis containers
language: python
python:
    - "3.6"
install:
  - pip install -r Requirements.txt
  - pip install coverage

script:
  -  python -m pytest --cov
  
after_success: 
- coveralls
